apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-connector
  template:
    metadata:
      labels:
        app: bank-connector
    spec:
      containers:
      - name: bank-connector
        image: {{ .Values.bank_connector.image }}
        envFrom:
        - secretRef:
            name: bankers-bank-secret
        - configMapRef:
            name: bankers-bank-env
        ports:
        - containerPort: {{ .Values.bank_connector.port }}
        - containerPort: 8001
        command: ["uvicorn", "bank_connector.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.bank_connector.port }}", "--ssl-certfile", "/certs/server.pem", "--ssl-keyfile", "/certs/server.key"]
---
apiVersion: v1
kind: Service
metadata:
  name: bank-connector
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.bank_connector.port }}
    targetPort: {{ .Values.bank_connector.port }}
  - port: 8001
    targetPort: 8001
  selector:
    app: bank-connector
