apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-connector
  template:
    metadata:
      labels:
        app: bank-connector
    spec:
      containers:
      - name: bank-connector
        image: {{ .Values.bank_connector.image }}
        envFrom:
        - configMapRef:
            name: bankers-bank-env
        ports:
        - containerPort: {{ .Values.bank_connector.port }}
        command: ["uvicorn", "bank_connector.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.bank_connector.port }}"]
---
apiVersion: v1
kind: Service
metadata:
  name: bank-connector
spec:
  ports:
  - port: {{ .Values.bank_connector.port }}
    targetPort: {{ .Values.bank_connector.port }}
  selector:
    app: bank-connector
