apiVersion: v1
kind: ConfigMap
metadata:
  name: bankers-bank-env
  labels:
    app: bankers-bank
data:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}"
  ASSET_DB_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}"
  CREDIT_DB_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}"
  KAFKA_BOOTSTRAP: "redpanda:{{ .Values.redpanda.port }}"
  REDIS_URL: "redis://redis:{{ .Values.redis.port }}/0"
