apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankers-bank
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.bank_connector.path }}
        pathType: Prefix
        backend:
          service:
            name: bank-connector
            port:
              number: {{ .Values.bank_connector.port }}
      - path: {{ .Values.treasury_orchestrator.path }}
        pathType: Prefix
        backend:
          service:
            name: treasury-orchestrator
            port:
              number: {{ .Values.treasury_orchestrator.port }}
