apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}
        args: ["--config.file=/etc/prometheus/prometheus.yml"]
        ports:
        - containerPort: {{ .Values.prometheus.port }}
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: bankers-bank
        static_configs:
          - targets:
            - bank-connector:8001
            - treasury-orchestrator:8001
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  ports:
  - port: 8001
    targetPort: {{ .Values.prometheus.port }}
  selector:
    app: prometheus
