apiVersion: batch/v1
kind: CronJob
metadata:
  name: audit-exporter
  labels:
    app: audit-exporter
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: audit-exporter
              image: your-repo/treasury:v1.4.3 # pin image tag
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              command: ["/app/bin/audit-export"]
              args:
                - --batch-size=5000
                - --cutoff-lag-min=5
                - --max-batches=10
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: treasury-secrets
                      key: DATABASE_URL
                - name: AUDIT_EXPORT_DIR
                  value: /var/lib/audit-exports
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
              volumeMounts:
                - name: audit-exports
                  mountPath: /var/lib/audit-exports
          volumes:
            - name: audit-exports
              emptyDir: {}
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
