# Values support envsubst; see `.env.example` for local configuration.
ingress:
  host: bankers-bank.local

bank_connector:
  image: bank_connector:latest
  port: 8080
  path: /

enableAlerting: true

treasury_orchestrator:
  image: treasury_orchestrator:latest
  port: 8000
  path: /treasury

quant_consumer:
  image: quant_consumer:latest

postgres:
  image: postgres:13
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db: ${POSTGRES_DB}
  port: 5432

redpanda:
  image: docker.redpanda.com/vectorized/redpanda:latest
  port: 9092

redis:
  image: redis:7
  port: 6379

prometheus:
  image: prom/prometheus
  port: 9090

grafana:
  image: grafana/grafana
  port: 3000
