bank_connector:
  image: bank_connector:latest
  port: 8080

treasury_orchestrator:
  image: treasury_orchestrator:latest
  port: 8000

quant_consumer:
  image: quant_consumer:latest

postgres:
  image: postgres:13
  username: bank
  password: bank
  db: bank
  port: 5432

redpanda:
  image: docker.redpanda.com/vectorized/redpanda:latest
  port: 9092

redis:
  image: redis:7
  port: 6379

prometheus:
  image: prom/prometheus
  port: 9090

grafana:
  image: grafana/grafana
  port: 3000
