openapi: 3.1.0
info:
  title: Bankers-Bank Core API
  version: 0.1.0
paths:
  /v1/accounts:
    post:
      summary: Open account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccount'
      responses:
        "201":
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /ltv/calculate:
    post:
      summary: Calculate Loan-to-Value (LTV) ratio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LTVRequest'
      responses:
        "200":
          description: LTV calculation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LTVResponse'
        "400":
          description: Invalid input
components:
  schemas:
    NewAccount:
      type: object
      required: [legal_name, type, currency]
      properties:
        legal_name: { type: string }
        type:       { type: string, enum: [DEPOSIT, SWEEP, CREDIT_LINE] }
        currency:   { type: string, pattern: '^[A-Z]{3}$' }
    Account:
      allOf:
        - $ref: '#/components/schemas/NewAccount'
        - type: object
          properties:
            id: { type: string, format: uuid }
            created_at: { type: string, format: date-time }
    LTVRequest:
      type: object
      required:
        - collateral_value
        - loan_amount
      properties:
        collateral_value:
          type: number
          description: The value of the collateral asset
        loan_amount:
          type: number
          description: The amount of the loan
    LTVResponse:
      type: object
      properties:
        ltv:
          type: number
          description: The calculated loan-to-value ratio
