openapi: 3.1.0
info:
  title: Bankers-Bank Core API
  version: 0.1.0
paths:
  /v1/accounts:
    post:
      summary: Open account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccount'
      responses:
        "201":
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
components:
  schemas:
    NewAccount:
      type: object
      required: [legal_name, type, currency]
      properties:
        legal_name: { type: string }
        type:       { type: string, enum: [DEPOSIT, SWEEP, CREDIT_LINE] }
        currency:   { type: string, pattern: '^[A-Z]{3}$' }
    Account:
      allOf:
        - $ref: '#/components/schemas/NewAccount'
        - type: object
          properties:
            id: { type: string, format: uuid }
            created_at: { type: string, format: date-time }
